
local LuaMS={}
function LuaMS.loader()
local ls = require("luasnip")
local s = ls.snippet
local sn = ls.snippet_node
local isn = ls.indent_snippet_node
local t = ls.text_node
local i = ls.insert_node
local f = ls.function_node
local c = ls.choice_node
local d = ls.dynamic_node
local r = ls.restore_node
local events = require("luasnip.util.events")
local ai = require("luasnip.nodes.absolute_indexer")
local extras = require("luasnip.extras")
local l = extras.lambda
local rep = extras.rep
local p = extras.partial
local m = extras.match
local n = extras.nonempty
local dl = extras.dynamic_lambda
local fmt = require("luasnip.extras.fmt").fmt
local fmta = require("luasnip.extras.fmt").fmta
local conds = require("luasnip.extras.expand_conditions")
local postfix = require("luasnip.extras.postfix").postfix
local types = require("luasnip.util.types")
local parse = require("luasnip.util.parser").parse_snippet
local ms = ls.multi_snippet
local k = require("luasnip.nodes.key_indexer").new_key

local function fn(
  args     -- text from i(2) in this example i.e. { { "456" } }
  --parent,   -- parent snippet or parent node
  --user_args -- user_args from opts.user_args 
)
   return args[1][1]
end

function Nl()
	return 	t({'', ''})
end

ls.add_snippets("tex",
{
	s("pre-platex",{
		t("haste on"),i(0),t("the venus")
	}),

	s("pre-lualatex",{
		t({"anti","parabolalism"})
	}),

	s({trig="begin", name="environment", dscr="basic environment"}, {
	t '\\begin{',i(1,'environment'),t'}',Nl(),
	t({'', ''}),
	t({'  '}),i(0),
	t({'', ''}),
	t'\\end{',f(fn,{1}),t'}',
	}),

	s({trig="sniplua", name="snippet_Lua", dscr="snippet fot LuaLaTeX"}, {
		t("\\documentclass[10.5ptj]{ltjsarticle}%using LuaLaTeX"),
		Nl(),t("\\usepackage{plautopatch}"),
		Nl(),t("\\usepackage{amssymb}"),
		Nl(),t("\\usepackage{mathtools}"),
		Nl(),t("\\usepackage{amsthm}"),
		Nl(),t("\\usepackage{enumerate}"),
		Nl(),t("\\usepackage{array}"),
		Nl(),t("\\usepackage{tikz}"),
		Nl(),t("\\usepackage{circuitikz}"),
		Nl(),t("\\usepackage{indentfirst}"),
		Nl(),t("\\usepackage{pb-diagram}"),
		Nl(),t("\\usepackage{siunitx}"),
		Nl(),t("\\usepackage{pgfplots}"),
		Nl(),t("\\usepackage{graphicx}"),
		Nl(),t("\\usepackage{here}"),
		Nl(),t("\\usepackage{tabularx}"),
		Nl(),t("\\usepackage{luatexja-fontspec}"),
		Nl(),t("\\usepackage{xcolor}"),
		Nl(),t("%setting font"),
		Nl(),t("\\setmainjfont[BoldFont=HaranoAjiGothic-Bold]{HaranoAjiMincho-Regular}"),
		Nl(),t("\\setsansjfont{HaranoAjiGothic-Medium}"),
		Nl(),t("\\usetikzlibrary{positioning}"),
		Nl(),t("\\usetikzlibrary{arrows}"),
		Nl(),t("\\usetikzlibrary{arrows.meta}"),
		Nl(),t("\\usetikzlibrary{calc}"),
		Nl(),
		Nl(),t("\\usepackage[top=25truemm,bottom=25truemm,left=20truemm,right=20truemm]{geometry}"),
		Nl(),t("\\numberwithin{equation}{subsection}"),
		Nl(),t("\\newcommand{\\itl}[1]{{\\it{#1}}}"),
		Nl(),t("\\newcommand{\\rmn}[1]{{\\rm{#1}}}"),
		Nl(),t("\\newcommand{\\bhline}[1]{\\noalign{\\hrule height #1}} "  ),
		Nl(),t("\\newcommand{\\movep}[0]{\\frac{\\rho V^2}{2}}"),
		Nl(),
		Nl(),t("\\theoremstyle{plain}"),
		Nl(),t("\\newtheorem{theorem}{Theorem}"),
		Nl(),t("\\newtheorem*{theorem*}{Theorem}"),
		Nl(),t("\\newtheorem{corollary}{Corollary}"),
		Nl(),t("\\newtheorem{lemma}{Lemma}"),
		Nl(),t("\\newtheorem{proposition}{Proposition}"),
		Nl(),t("\\newtheorem{example}{Example}"),
		Nl(),t("\\newtheorem{quiz}{Quiz}"),
		Nl(),t("\\theoremstyle{definition}"),
		Nl(),t("\\newtheorem{definition}{Definition}"),
		Nl(),t("\\setlength{\\columnseprule}{0.4pt}%真中線の太さ"),
		Nl(),t("\\pagestyle{myheadings}"),
		Nl(),
		Nl(),t("\\newcommand{\\TITLE}{"),i(1,"title"),t("}%タイトルを入力"),
		Nl(),
		Nl(),t("\\begin{document}"),
		Nl(),t("\\thispagestyle{empty}"),
		Nl(),t("\\markboth{\\textbf{\\TITLE}}{\\textbf{\\TITLE}}"),
		Nl(),
		Nl(),t("\\begin{center}"),
		Nl(),t("\\Huge{\\textbf{\\TITLE}}%title"),
		Nl(),t("\\end{center}"),
		Nl(),t("\\rightline{"),i(2,"author"),t("}"),
		Nl(),t("\\vspace{12pt}"),
		Nl(),t("\\section{"),i(0,"section"),t("}"),
		Nl(),
		Nl(),t("\\vfill"),
		Nl(),t("\\begin{flushright}"),
		Nl(),t("\\rightline{\\small{\\textbf{\\textsl{This document is generated by Lua\\LaTeX.}}}}"),
		Nl(),t("\\rightline{\\small{\\textbf{\\textsl{SEE YOU WAYFARER \\dots}}}}"),
		Nl(),t("\\end{flushright}"),
		Nl(),t("\\end{document}")
	}),
}
)
end
return LuaMS
